import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pre Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pre Production</h1>

        <p className={styles.description}>기술 블로그 만들기</p>
        <div className={styles.flexLow}>
          <p className={styles.code}>Next.js</p>
          <p className={styles.code}>emotion.js</p>
          <p className={styles.code}>Typescript</p>
        </div>
        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>티스토리 블로그</h2>
            <p>JS 클론코딩 및 42seoul 과제에 대한 포스팅</p>
            <p>2019-2021</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>2022</footer>
    </div>
  );
}
